import { useState } from 'react';
import { ArrowRight, ArrowUpRight, MagnifyingGlass, Plus, UploadSimple, FileText, Clock, FunnelSimple } from '@phosphor-icons/react';
import { useStore } from '../store';
import { DateText, Empty, Modal, Status } from './ui';
import type { CaseRecord } from '../domain/types';

export function Cases({onOpen,onImport}:{onOpen:(id:string)=>void;onImport:(id?:string)=>void}) {
 const {state,dispatch}=useStore(); const [search,setSearch]=useState('');const [district,setDistrict]=useState('All districts');const [status,setStatus]=useState('All cases');const [create,setCreate]=useState(false);const [title,setTitle]=useState('');const [newDistrict,setNewDistrict]=useState('North');const [station,setStation]=useState('');
 const filtered=state.cases.filter(c=>(status==='All cases'||c.status===status)&&(district==='All districts'||c.district===district)&&`${c.title} ${c.reference} ${c.district}`.toLowerCase().includes(search.toLowerCase()));
 const featured=state.cases.find(c=>c.id==='c1')||state.cases[0];
 function add(e:React.FormEvent){e.preventDefault();if(!title.trim()||!station.trim())return;const time=new Date().toISOString();const record:CaseRecord={id:crypto.randomUUID(),reference:`DEMO/2026/${String(state.cases.length+419).padStart(4,'0')}`,title:title.trim(),district:newDistrict,station:station.trim(),officer:'A. Sharma',status:'Active',updated:time,summary:'New demonstration case. Attach documents or load a prepared evidence pack to begin.'};dispatch({type:'add-case',record,time});setCreate(false);setTitle('');setStation('');onOpen(record.id);}
 return <div className="page cases-page"><div className="page-title"><div><h1>Case register</h1><p>Assigned investigations, connected evidence and review decisions.</p></div><div className="actions"><button className="button" onClick={()=>onImport()}><UploadSimple size={17}/>Import evidence</button><button className="button primary" onClick={()=>setCreate(true)}><Plus size={17}/>New case</button></div></div>
 <div className="case-tabs">{['All cases','Active','Under review','Closed'].map(s=><button key={s} className={status===s?'selected':''} onClick={()=>setStatus(s)}>{s}<span>{state.cases.filter(c=>s==='All cases'||c.status===s).length}</span></button>)}</div>
 <div className="register-layout"><section className="register"><div className="register-tools"><label className="search"><MagnifyingGlass size={18}/><input aria-label="Search cases" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by case, reference or district"/></label><label className="select-wrap"><FunnelSimple size={16}/><select aria-label="Filter district" value={district} onChange={e=>setDistrict(e.target.value)}><option>All districts</option>{[...new Set(state.cases.map(c=>c.district))].map(d=><option key={d}>{d}</option>)}</select></label></div>
 <div className="register-caption"><span>{filtered.length} investigations</span><span>Sorted by case reference</span></div>
 <div className="table-scroll"><table className="case-table"><thead><tr><th>Case / subject</th><th>Status</th><th>District</th><th>Review</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td><button className="case-title-link" onClick={()=>onOpen(c.id)}><span className="reference">{c.reference}</span><strong>{c.title}</strong><span className="case-station">{c.station}</span></button></td><td><Status status={c.status}/></td><td>{c.district}</td><td><span className="pending-number">{state.leads.filter(l=>l.caseId===c.id&&l.status==='unreviewed').length}</span><span className="muted"> pending</span></td><td><button className="icon-button" onClick={()=>onOpen(c.id)} aria-label={`Open ${c.title}`}><ArrowUpRight size={19}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty title="No matching cases">Try a different search or clear the district filter.</Empty>}
 <div className="register-foot"><FileText size={16}/><span>Fictional records for demonstration. No live case data.</span></div></section>
 <aside className="continue-panel"><div className="panel-kicker"><Clock size={16}/>Continue investigation</div><div className="continue-ref">{featured.reference}</div><h2>{featured.title}</h2><p>{featured.summary}</p><dl className="summary-dl"><div><dt>Investigating officer</dt><dd>{featured.officer}</dd></div><div><dt>Last updated</dt><dd><DateText value={featured.updated}/></dd></div><div><dt>Source documents</dt><dd>{state.sources.filter(s=>s.caseId===featured.id).length} records</dd></div></dl><button className="button primary wide" onClick={()=>onOpen(featured.id)}>Open investigation<ArrowRight size={18}/></button><div className="small-note">Review a connection. Follow it to the source.</div></aside></div>
 <section className="recent-section"><div className="section-heading"><h2>Recent activity</h2><span className="muted">Across your cases</span></div><div className="recent-list">{state.activity.slice(0,4).map(a=><button key={a.id} className="recent-item" onClick={()=>onOpen(a.caseId)}><div className="activity-icon"><FileText size={18}/></div><div><strong>{a.title}</strong><p>{a.detail}</p></div><DateText value={a.time}/><ArrowUpRight size={16}/></button>)}</div></section>
 <Modal open={create} onClose={()=>setCreate(false)} title="Create a case" description="Create a local demonstration record. All changes stay in this browser."><form onSubmit={add} className="form"><label>Case subject<input required maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Enter investigation subject"/></label><div className="form-row"><label>District<select value={newDistrict} onChange={e=>setNewDistrict(e.target.value)}>{['North','Central','East','South','West','New Delhi'].map(d=><option key={d}>{d}</option>)}</select></label><label>Station<input required maxLength={80} value={station} onChange={e=>setStation(e.target.value)} placeholder="Station name"/></label></div><p className="muted small">A demonstration reference will be assigned on creation.</p><div className="form-actions"><button type="button" className="button" onClick={()=>setCreate(false)}>Cancel</button><button className="button primary" type="submit">Create case</button></div></form></Modal></div>;
}
