import { useEffect, useRef, useState } from 'react';
import { Check, FileText, UploadSimple, WarningCircle, Paperclip, X } from '@phosphor-icons/react';
import { useStore } from '../store';
import { Modal } from './ui';
export interface Attachment {id:string;caseId:string;name:string;url:string;type:string;text?:string;}
export function ImportEvidence({open,onClose,caseId,onAttachment}:{open:boolean;onClose:()=>void;caseId:string;onAttachment:(a:Attachment)=>void}){
 const {state,dispatch}=useStore();const [selected,setSelected]=useState(caseId);const [mode,setMode]=useState<'pack'|'file'>('pack');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState(false);const input=useRef<HTMLInputElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
 useEffect(()=>{if(open){setSelected(caseId);setError('');setSuccess(false);setBusy(false);}},[open,caseId]);useEffect(()=>()=>clearTimeout(timer.current),[]);
 const loaded=state.loadedPacks.includes(selected)||state.loadedPacks.some(p=>p.includes(selected));
 function load(){setBusy(true);timer.current=setTimeout(()=>{dispatch({type:'import-pack',caseId:selected,time:new Date().toISOString()});setBusy(false);setSuccess(true);},650);}
 async function attach(file?:File){if(!file)return;setError('');if(file.size>20*1024*1024){setError('This file exceeds 20 MB. Choose a smaller file.');return;}const ext=file.name.split('.').pop()?.toLowerCase();if(!['pdf','png','jpg','jpeg','webp','txt'].includes(ext||'')){setError('Choose a PDF, PNG, JPEG, WebP or plain text file.');return;}try{const type=ext==='txt'?'text/plain':ext==='pdf'?'application/pdf':`image/${ext==='jpg'?'jpeg':ext}`;const url=URL.createObjectURL(new Blob([file],{type}));const text=type==='text/plain'?await file.text():undefined;onAttachment({id:crypto.randomUUID(),caseId:selected,name:file.name,url,type,text});setSuccess(true);}catch{setError('The file could not be opened. Try selecting it again.');}}
 return <Modal open={open} onClose={()=>{clearTimeout(timer.current);onClose();}} title="Import evidence" description="Choose a prepared record pack or attach a file for preview."><div className="form"><label>Assign to case<select value={selected} onChange={e=>{setSelected(e.target.value);setSuccess(false);}}>{state.cases.map(c=><option key={c.id} value={c.id}>{c.reference} · {c.title}</option>)}</select></label><div className="segmented"><button className={mode==='pack'?'active':''} onClick={()=>{setMode('pack');setSuccess(false);}}>Demonstration pack</button><button className={mode==='file'?'active':''} onClick={()=>{setMode('file');setSuccess(false);}}>Local attachment</button></div>
 {mode==='pack'?<><div className="pack-preview"><FileText size={27}/><div><strong>Supplementary witness record</strong><p>A fictional statement with a prepared connection to this case.</p><span className="small muted">1 source document and 1 suggested lead</span></div></div><div className="notice"><WarningCircle size={17}/><span>This imports prepared results. No OCR, AI model or live data connection runs.</span></div>{busy&&<div className="processing" role="status"><div className="loading-bar"/>Loading demonstration records…</div>}{(success||loaded)&&<p className="success-message" role="status"><Check size={18}/>{success?'Evidence pack loaded. Review it in the case workspace.':'This case already contains the demonstration pack.'}</p>}<div className="form-actions"><button className="button" onClick={onClose}>Close</button><button className="button primary" disabled={busy||success||loaded} onClick={load}><UploadSimple size={17}/>{busy?'Loading…':loaded||success?'Pack loaded':'Load evidence pack'}</button></div></>:<><button className="upload-zone" onClick={()=>input.current?.click()}><Paperclip size={29}/><strong>Select a file</strong><span>PDF, image or plain text. Up to 20 MB.</span></button><input ref={input} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt" className="sr-only" aria-label="Select local evidence file" onChange={e=>{void attach(e.target.files?.[0]);e.target.value='';}}/><p className="small muted">Attachments stay in this browser session. They can be previewed, but are not analysed or added to generated findings.</p>{error&&<p className="error-message" role="alert"><X size={16}/>{error}</p>}{success&&<p className="success-message" role="status"><Check size={18}/>Attached for preview. Open the source register to view it.</p>}<div className="form-actions"><button className="button primary" onClick={onClose}>Done</button></div></>}
 </div></Modal>;
}
