import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, ArrowsLeftRight, CaretDown, CaretRight, Check, Checks, ClockCounterClockwise, FileText, FunnelSimple, Graph, LockKey, MagnifyingGlass, MapPin, NotePencil, Paperclip, SidebarSimple, Sparkle, Table, UploadSimple, WarningCircle, X } from '@phosphor-icons/react';
import { useStore } from '../store';
import { DateText, Drawer, Empty, KindIcon, Modal, SourceLink, Status } from './ui';
import { GraphView } from './GraphView';
import type { Attachment } from './ImportEvidence';
import type { Entity, Lead, Relation, ReviewStatus, SourceRecord } from '../domain/types';
import { initialInvestigationView } from '../presentation';
const kinds=['All entities','Person','Phone','Account','Location','Case','Organization'];
const pageOf=(s:SourceRecord)=>s.fullText.match(/Page (\d+)/)?.[1]||'1';

export function Investigation({caseId,onCases,onImport,onReports,attachments,onToast}:{caseId:string;onCases:()=>void;onImport:()=>void;onReports:()=>void;attachments:Attachment[];onToast:(m:string)=>void}) {
 const {state,dispatch}=useStore();const current=state.cases.find(c=>c.id===caseId)!;
 const caseLeads=state.leads.filter(l=>l.caseId===caseId);
 const [leadId,setLeadId]=useState(caseLeads[0]?.id||'');const lead=caseLeads.find(l=>l.id===leadId);
 const [tab,setTab]=useState<string>(initialInvestigationView);const [leftTab,setLeftTab]=useState('Leads');const [queueFilter,setQueueFilter]=useState('All decisions');const [expanded,setExpanded]=useState(false);const [summary,setSummary]=useState(false);const [sourcesOpen,setSourcesOpen]=useState(false);
 const [query,setQuery]=useState('');const [from,setFrom]=useState('2026-06-01');const [to,setTo]=useState('2026-09-30');const [kind,setKind]=useState('All entities');
 const [sourceId,setSourceId]=useState(lead?.sourceIds[0]||'');const [relation,setRelation]=useState<Relation>();const [entity,setEntity]=useState<Entity>();const [fullSource,setFullSource]=useState<SourceRecord>();const [preview,setPreview]=useState<Attachment>();
 const [compare,setCompare]=useState(false);const [activity,setActivity]=useState(false);const [copilot,setCopilot]=useState(false);const [answer,setAnswer]=useState('');const [askText,setAskText]=useState('');const [mobileEvidence,setMobileEvidence]=useState(false);
 const [filtersOpen,setFiltersOpen]=useState(false);
 const [review,setReview]=useState<ReviewStatus>();const [notes,setNotes]=useState('');const [noteError,setNoteError]=useState('');
 const source=state.sources.find(s=>s.id===sourceId);const sourceList=lead?state.sources.filter(s=>lead.sourceIds.includes(s.id)):[];
 const inRange=(date:string)=>(!from||date.slice(0,10)>=from)&&(!to||date.slice(0,10)<=to);
 const invalidRange=!!from&&!!to&&from>to;
 const baseRelations=useMemo(()=>state.relations.filter(r=>r.sourceIds.every(id=>!state.sources.find(s=>s.id===id)?.restricted)&&r.sourceIds.some(id=>state.sources.find(s=>s.id===id)?.caseId===caseId)||r.leadIds.some(id=>caseLeads.some(l=>l.id===id))&&r.sourceIds.every(id=>!state.sources.find(s=>s.id===id)?.restricted)),[state,caseId]);
 const filteredRelations=baseRelations.filter(r=>!invalidRange&&inRange(r.date));
 const relatedIds=new Set(filteredRelations.flatMap(r=>[r.source,r.target]));
 const entities=state.entities.filter(e=>relatedIds.has(e.id)&&(kind==='All entities'||e.kind===kind)&&(!query||`${e.label} ${e.subtitle} ${e.kind}`.toLowerCase().includes(query.toLowerCase())));
 const ids=new Set(entities.map(e=>e.id));const relations=filteredRelations.filter(r=>ids.has(r.source)&&ids.has(r.target));
 const shownLeads=caseLeads.filter(l=>(leftTab==='Leads'||queueFilter==='All decisions'||l.status===queueFilter)&&(!query||`${l.title} ${l.summary}`.toLowerCase().includes(query.toLowerCase())||l.entityIds.some(id=>ids.has(id)))&&!invalidRange&&inRange(l.date));
 const selectedDateOutside=lead&&!inRange(lead.date);
 function chooseLead(l:Lead){setLeadId(l.id);setSourceId(l.sourceIds[0]||'');setRelation(undefined);setEntity(undefined);setAnswer('');setCopilot(false);setExpanded(false);}
 function chooseRelation(r:Relation){const owner=caseLeads.find(l=>r.leadIds.includes(l.id));if(owner&&owner.id!==leadId){setLeadId(owner.id);setSourceId(owner.sourceIds[0]||'');}setRelation(r);setSourceId(r.sourceIds[0]);setEntity(undefined);setCopilot(false);setMobileEvidence(true);}
 function chooseEntity(e:Entity){setEntity(e);const rel=relations.find(r=>r.source===e.id||r.target===e.id);if(rel){const owner=caseLeads.find(l=>rel.leadIds.includes(l.id));if(owner&&owner.id!==leadId){setLeadId(owner.id);}setRelation(rel);setSourceId(rel.sourceIds[0]);}setCopilot(false);setMobileEvidence(true);}
 function openReview(status:ReviewStatus){if(!lead)return;setNotes(lead.notes||'');setNoteError('');setReview(status);}
 function saveReview(e:React.FormEvent){e.preventDefault();if(!lead||!review)return;if((review==='dismissed'||review==='correction')&&!notes.trim()){setNoteError('Add a reason so another reviewer can understand this decision.');return;}dispatch({type:'review',id:lead.id,status:review,notes:notes.trim(),time:new Date().toISOString()});setReview(undefined);onToast(review==='reviewed'?'Lead marked reviewed. It can now be included in a report.':review==='dismissed'?'Lead dismissed. The decision is recorded in activity.':'Correction requested. The source record remains unchanged.');}
 function ask(value:string){if(!lead){setAnswer('Select a lead to inspect its prepared evidence.');return;}const q=value.toLowerCase();if(q.includes('conflict')||q.includes('uncertain'))setAnswer(lead.kind==='conflict'?lead.reason:`${lead.reason} Identity and intent are not established by this connection.`);else if(q.includes('source')||q.includes('evidence'))setAnswer(`This lead references ${sourceList.filter(s=>!s.restricted).length} accessible source records. Open a reference below to inspect its passage and date.`);else if(q.includes('explain')||q.includes('connection'))setAnswer(lead.reason);else setAnswer('This prototype supports explaining the selected connection, listing its sources and showing conflicts. It does not run a language model. Choose one of those questions.');setAskText('');}
 const canCompare=lead?.kind==='conflict';const personIds=canCompare?lead?.entityIds||[]:[];const people=state.entities.filter(e=>e.kind==='Person'&&personIds.includes(e.id)).slice(0,2);
 const documentView=(s:SourceRecord)=>s.restricted?<div className="restricted"><LockKey size={30}/><h3>Access unavailable in this view</h3><p>This demonstration record illustrates a restricted source. Its contents are not displayed.</p></div>:<><div className="document-meta"><span>{s.type}</span><span><DateText value={s.date}/></span><span>{s.pages} pages</span><span>Fictional record</span></div><article className="document-paper"><div className="document-letterhead">CHAKRA / DEMONSTRATION RECORD</div><h2>{s.title}</h2><p className="document-reference">Source {s.id.toUpperCase()} · {state.cases.find(c=>c.id===s.caseId)?.reference}</p><div className="document-rule"/><p className="document-section">Referenced passage · page {pageOf(s)}</p><mark>{s.excerpt}</mark>{s.fullText.split('\n\n').filter(p=>p!==s.excerpt).map((p,i)=><p key={i}>{p}</p>)}</article></>;
 const evidence=<div className="evidence-content">{copilot?<><div className="evidence-section"><div className="panel-title"><Sparkle size={18}/><h3>Ask Chakra</h3></div><p className="small muted">Prepared responses for the selected lead. No AI service is connected.</p><div className="prompt-list">{['Explain this connection','List supporting sources','Show conflicting evidence'].map(p=><button key={p} onClick={()=>ask(p)}>{p}<ArrowUpRight size={14}/></button>)}</div>{answer&&<div className="answer" aria-live="polite"><span className="answer-label">Prepared response</span><p>{answer}</p>{sourceList.filter(s=>!s.restricted).map(s=><SourceLink key={s.id} onClick={()=>setFullSource(s)}>{s.id.toUpperCase()} · {s.type}, p. {pageOf(s)}</SourceLink>)}</div>}<form className="ask-form" onSubmit={e=>{e.preventDefault();if(askText.trim())ask(askText);}}><label htmlFor="ask">Question about this lead</label><div><input id="ask" value={askText} onChange={e=>setAskText(e.target.value)} placeholder="Explain this connection"/><button className="icon-button" type="submit" aria-label="Ask question"><ArrowRight size={18}/></button></div></form></div></>:lead?<><div className="evidence-section"><div className="panel-title"><FileText size={18}/><h3>Connection details</h3></div><div className="evidence-heading"><Status status={lead.status}/><span className="reference">{lead.id.toUpperCase()}</span></div><h2>{lead.title}</h2><p>{lead.reason}</p>{entity&&<div className="entity-selection"><KindIcon kind={entity.kind}/><div><span className="small muted">Selected {entity.kind.toLowerCase()}</span><strong>{entity.label}</strong></div></div>}{relation&&<div className="relationship-selection">Selected relationship<strong>{relation.label}</strong><DateText value={relation.date}/></div>}{lead.kind==='conflict'&&<div className="notice"><WarningCircle size={17}/><span>Conflicting identity details. Compare records before making a decision.</span></div>}{canCompare&&<button className="text-button" onClick={()=>setCompare(true)}><ArrowsLeftRight size={16}/>Compare identities</button>}</div>
 <div className="evidence-section"><div className="section-heading"><h3>Supporting evidence</h3><span className="count-label">{sourceList.length} sources</span></div><div className="source-tabs">{sourceList.map((s,i)=><button key={s.id} onClick={()=>setSourceId(s.id)} className={s.id===sourceId?'active':''}>{String(i+1).padStart(2,'0')}<span>{s.type}</span></button>)}</div>{source&&<div className="source-excerpt">{source.restricted?<div className="notice"><LockKey size={18}/>Restricted source. Preview unavailable.</div>:<><div className="excerpt-heading"><FileText size={16}/><strong>{source.title}</strong></div><span className="small muted">{state.cases.find(c=>c.id===source.caseId)?.reference} · Page {pageOf(source)}</span><blockquote>{source.excerpt}</blockquote><SourceLink onClick={()=>setFullSource(source)}>Open source document</SourceLink></>}</div>}</div>
 <div className="evidence-section review-section"><h3>Review decision</h3><p className="small muted">Review confirms that you examined the lead. It is not a finding of guilt.</p>{lead.notes&&<div className="review-note"><span>Reviewer note</span><p>{lead.notes}</p></div>}<button className="button primary wide" onClick={()=>openReview('reviewed')}><Check size={17}/>{lead.status==='reviewed'?'Edit review note':'Mark reviewed'}</button><div className="review-secondary"><button className="button" onClick={()=>openReview('dismissed')}>Dismiss lead</button><button className="button" onClick={()=>openReview('correction')}><NotePencil size={15}/>Correction</button></div>{lead.status==='reviewed'&&<button className="text-button" onClick={onReports}>Include in report<ArrowRight size={15}/></button>}</div></>:<Empty title="Select a lead">Choose a suggested connection to inspect its evidence.</Empty>}</div>;
 return <div className={`investigation ${filtersOpen?'filters-open':''}`}><div className="investigation-title"><div className="case-breadcrumb"><button className="text-button" onClick={onCases}><ArrowLeft size={15}/>Cases</button><span>/</span><span className="reference">{current.reference}</span><Status status={current.status}/></div><div className="case-heading"><h1>{current.title}</h1><div className="actions"><button className="button" onClick={()=>setActivity(true)} aria-label="Open case activity"><ClockCounterClockwise size={17}/><span className="desktop-label">Activity</span></button><button className="button" aria-label="Import evidence" onClick={onImport}><UploadSimple size={17}/><span className="desktop-label">Import evidence</span></button></div></div><div className="case-subline"><span>{current.station}, {current.district} district</span><button className="text-button" onClick={()=>setSummary(!summary)}>{summary?<CaretDown size={13}/>:<CaretRight size={13}/>}Case summary</button><button className="text-button" onClick={()=>setSourcesOpen(true)}><FileText size={14}/>Source register ({state.sources.filter(s=>s.caseId===caseId).length+attachments.filter(a=>a.caseId===caseId).length})</button></div>{summary&&<div className="case-summary"><p>{current.summary}</p><span>Assigned to {current.officer}</span></div>}</div>
 <div className="investigation-toolbar"><div><span className="investigation-eyebrow">Case workspace</span><strong>{caseLeads.length} leads <span>·</span> {caseLeads.filter(l=>l.status==='reviewed').length} reviewed</strong></div><button className="button" aria-expanded={filtersOpen} aria-controls="investigation-filter-controls" onClick={()=>setFiltersOpen(v=>!v)}><FunnelSimple size={16}/>Filters{(query||kind!=='All entities'||from!=='2026-06-01'||to!=='2026-09-30')&&<span className="filter-active-dot"/>}<CaretDown size={13}/></button></div>
 <div id="investigation-filter-controls" className="investigation-filters"><label className="search"><MagnifyingGlass size={17}/><input aria-label="Search investigation" placeholder="Find an entity or connection" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="date-range"><label><span>From</span><input aria-label="From date" type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><span className="muted">to</span><label><span>To</span><input aria-label="To date" type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><label className="select-wrap"><FunnelSimple size={16}/><select aria-label="Entity type" value={kind} onChange={e=>setKind(e.target.value)}>{kinds.map(k=><option key={k}>{k}</option>)}</select></label><button className="text-button" onClick={()=>{setQuery('');setKind('All entities');setFrom('2026-06-01');setTo('2026-09-30');}}>Reset filters</button></div>{invalidRange&&<p role="alert" className="filter-error">The end date must be on or after the start date.</p>}
 <div className="workbench"><aside className="lead-panel"><div className="lead-tabs">{['Leads','Review queue'].map(t=><button key={t} onClick={()=>setLeftTab(t)} className={leftTab===t?'active':''}>{t}<span>{t==='Leads'?caseLeads.length:caseLeads.filter(l=>l.status!=='unreviewed').length}</span></button>)}</div>{leftTab==='Review queue'&&<select className="queue-filter" aria-label="Review status" value={queueFilter} onChange={e=>setQueueFilter(e.target.value)}><option>All decisions</option><option value="unreviewed">To review</option><option value="reviewed">Reviewed</option><option value="dismissed">Dismissed</option><option value="correction">Correction requested</option></select>}<div className="lead-list">{shownLeads.map((l,i)=><button className={`lead-row ${l.id===leadId?'selected':''}`} key={l.id} onClick={()=>chooseLead(l)}><div className="lead-row-top"><span className="lead-index">{String(i+1).padStart(2,'0')}</span>{l.kind==='conflict'?<span className="conflict-tag"><WarningCircle size={13}/>Conflict</span>:<Status status={l.status}/>}</div><strong>{l.title}</strong><p>{l.summary}</p><div className="lead-row-foot"><span><FileText size={13}/>{l.sourceIds.length} sources</span>{l.status==='reviewed'?<Checks size={15}/>:<ArrowUpRight size={15}/>}</div></button>)}{!shownLeads.length&&<Empty title="No leads in this view">Adjust the filters or import a demonstration pack.</Empty>}</div><div className="lead-panel-foot"><LockKey size={14}/><span>Demonstration access scope</span></div></aside>
 <section className="canvas-panel"><div className="view-tabs">{[{name:'Graph',icon:Graph},{name:'Timeline',icon:ClockCounterClockwise},{name:'Locations',icon:MapPin},{name:'Table',icon:Table}].map(({name,icon:I})=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><I size={16}/>{name}</button>)}<button className="icon-button mobile-evidence-toggle" aria-label="Open evidence panel" onClick={()=>setMobileEvidence(true)}><SidebarSimple size={19}/></button></div><div className="canvas-caption"><span>{lead?.title||'Case connections'}</span><button className="text-button evidence-action" onClick={()=>{setCopilot(false);setMobileEvidence(true);}}><FileText size={16}/>Evidence</button><button className="text-button" onClick={()=>{setCopilot(!copilot);setMobileEvidence(true);}}><Sparkle size={16}/>Ask Chakra</button></div>{selectedDateOutside&&<div className="notice small">Selected lead falls outside the date filter.</div>}
 {entities.length===0?<Empty title="No entities match these filters" action={<button className="button" onClick={()=>{setQuery('');setKind('All entities');setFrom('');setTo('');}}>Clear filters</button>}>Try a wider date range or another entity type.</Empty>:tab==='Graph'?<GraphView entities={entities} relations={relations} lead={lead} onRelation={chooseRelation} onEntity={chooseEntity} expanded={expanded||kind!=='All entities'||!!query} onExpand={()=>setExpanded(!expanded)}/>:tab==='Timeline'?<div className="timeline-view"><div className="timeline-heading"><h3>Evidence chronology</h3><p>Dates refer to the source assertions shown.</p></div>{[...relations].sort((a,b)=>a.date.localeCompare(b.date)).map(r=><button key={r.id} className={`timeline-event ${relation?.id===r.id?'selected':''}`} onClick={()=>chooseRelation(r)}><DateText value={r.date}/><i/><div><strong>{r.label}</strong><p>{state.entities.find(e=>e.id===r.source)?.label} <ArrowRight size={12}/> {state.entities.find(e=>e.id===r.target)?.label}</p><span>{r.sourceIds.length} source references {r.inferred?' · Suggested link':''}</span></div><ArrowUpRight size={15}/></button>)}{relations.length===0&&<Empty title="No relationships in this view">Select All entities to restore complete paths.</Empty>}</div>:tab==='Locations'?<div className="locations-view"><div className="location-schematic"><div className="location-label">Illustrative locations</div><div className="schematic-route route-one"/><div className="schematic-route route-two"/>{entities.filter(e=>e.kind==='Location').map((e,i)=><button key={e.id} className="location-point" style={{left:`${25+(i%2)*38}%`,top:`${30+Math.floor(i/2)*25+(i%2)*24}%`}} onClick={()=>chooseEntity(e)}><MapPin size={23} weight="fill"/><strong>{e.label}</strong></button>)}</div><p className="small muted location-disclaimer">Schematic only. Positions do not represent precise coordinates, travel routes or tower coverage.</p>{entities.filter(e=>e.kind==='Location').length===0&&<Empty title="No locations in this selection">Choose All entities or expand the date range.</Empty>}{entities.filter(e=>e.kind==='Location').map(e=><button className="location-record" key={e.id} onClick={()=>chooseEntity(e)}><MapPin size={20}/><div><strong>{e.label}</strong><p>{e.subtitle}</p></div><ArrowUpRight size={16}/></button>)}</div>:<div className="table-scroll entity-table-wrap"><table className="entity-table"><thead><tr><th>Entity</th><th>Type</th><th>Context</th><th/></tr></thead><tbody>{entities.map(e=><tr key={e.id}><td><button onClick={()=>chooseEntity(e)} className="entity-table-name"><KindIcon kind={e.kind}/>{e.label}</button></td><td>{e.kind}</td><td>{e.subtitle}</td><td><button className="icon-button" aria-label={`Inspect ${e.label}`} onClick={()=>chooseEntity(e)}><ArrowUpRight size={15}/></button></td></tr>)}</tbody></table></div>}
 <div className="canvas-footer"><span><span className="tiny-key"/>Evidence-backed assertions</span><span>Human review required</span></div></section><aside className="evidence-panel"><div className="evidence-top"><span>{copilot?'Investigation assistant':'Evidence & review'}</span>{copilot?<button className="icon-button" aria-label="Return to evidence" onClick={()=>setCopilot(false)}><X size={16}/></button>:<FileText size={17}/>}</div>{evidence}</aside></div>
 <div className="mobile-evidence"><Drawer open={mobileEvidence&&window.innerWidth<1280} onClose={()=>setMobileEvidence(false)} title={copilot?'Ask Chakra':'Evidence & review'}>{evidence}</Drawer></div>
 <Drawer open={activity} onClose={()=>setActivity(false)} title="Case activity"><div className="drawer-description">{current.reference}<p>Local demonstration history. Not an immutable audit log.</p></div><div className="activity-feed">{state.activity.filter(a=>a.caseId===caseId).slice().reverse().map(a=><div key={a.id} className="activity-entry"><ClockCounterClockwise size={18}/><div><strong>{a.title}</strong><p>{a.detail}</p><DateText value={a.time}/></div></div>)}</div></Drawer>
 <Modal open={sourcesOpen} onClose={()=>setSourcesOpen(false)} title="Source register" description={`${current.reference}. Source records and session attachments.`} wide><div className="source-register">{state.sources.filter(s=>s.caseId===caseId).map(s=><button key={s.id} onClick={()=>setFullSource(s)}><FileText size={22}/><div><strong>{s.title}</strong><span>{s.type} · {s.pages} pages · {s.id.toUpperCase()}</span></div>{s.restricted?<LockKey size={18}/>:<ArrowUpRight size={17}/>}</button>)}{attachments.filter(a=>a.caseId===caseId).map(a=><button key={a.id} onClick={()=>setPreview(a)}><Paperclip size={21}/><div><strong>{a.name}</strong><span>Attached, not analysed · This session only</span></div><ArrowUpRight size={17}/></button>)}</div><div className="form-actions"><button className="button" onClick={()=>{setSourcesOpen(false);onImport();}}><UploadSimple size={16}/>Import evidence</button><button className="button primary" onClick={()=>setSourcesOpen(false)}>Done</button></div></Modal>
 <Modal open={!!fullSource} onClose={()=>setFullSource(undefined)} title="Source document" description="Preserved demonstration content. Source assertions may be incomplete or disputed." wide>{fullSource&&documentView(fullSource)}</Modal>
 <Modal open={!!preview} onClose={()=>setPreview(undefined)} title={preview?.name||'Attachment'} description="Attached, not analysed. This file stays in the current browser session." wide>{preview&&(preview.type==='text/plain'?<pre className="attachment-text">{preview.text}</pre>:preview.type.startsWith('image/')?<img className="attachment-image" src={preview.url} alt={`Attachment preview: ${preview.name}`}/>:<><object className="attachment-pdf" data={preview.url} type="application/pdf"><p>Your browser cannot preview this PDF inline. Use the link below.</p></object><a href={preview.url} target="_blank" rel="noreferrer" className="source-link">Open PDF in a new tab<ArrowUpRight size={14}/></a></>)}</Modal>
 <Modal open={compare} onClose={()=>setCompare(false)} title="Compare identity records" description="Similar names do not establish that two records describe the same person." wide><div className="identity-comparison">{people.map(e=><section key={e.id}><div className="compare-identity"><KindIcon kind="Person" size={23}/><div><span className="small muted">{e.id.toUpperCase()} / Person</span><h3>{e.label}</h3></div></div><dl><dt>Source description</dt><dd>{e.subtitle}</dd><dt>Recorded context</dt><dd>{e.caseIds.map(id=>state.cases.find(c=>c.id===id)?.reference).join(', ')}</dd><dt>Evidence assessment</dt><dd>{e.id==='e10'?'Different address and date of birth in the inquiry note. Described as a helpful neighbor.':'Verbal identification in a complaint. Identity document not provided.'}</dd></dl></section>)}</div><div className="notice"><WarningCircle size={18}/><span>These records remain separate. A shared first name is insufficient for merging identities.</span></div><div className="form-actions"><button className="button" onClick={()=>{setCompare(false);openReview('correction');}}>Request correction</button><button className="button primary" onClick={()=>setCompare(false)}>Keep records separate</button></div></Modal>
 <Modal open={!!review} onClose={()=>setReview(undefined)} title={review==='reviewed'?'Review this lead':review==='dismissed'?'Dismiss this lead':'Request a correction'} description={lead?.title}><form className="form" onSubmit={saveReview}><label>Reviewer note {review==='reviewed'?'(optional)':'(required)'}<textarea rows={5} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder={review==='dismissed'?'Explain why this connection should not be pursued.':review==='correction'?'Describe the source or identity detail that needs correction.':'Record what you checked and any remaining limitations.'}/></label>{noteError&&<p role="alert" className="error-message">{noteError}</p>}<p className="small muted">Your decision and note will appear in the local case history.</p><div className="form-actions"><button className="button" type="button" onClick={()=>setReview(undefined)}>Cancel</button><button className="button primary" type="submit">Save decision</button></div></form></Modal>
 </div>;
}
