import React from 'react';
import ReactDOM from 'react-dom/client';
import '@fontsource/ibm-plex-sans/400.css';
import '@fontsource/ibm-plex-sans/500.css';
import '@fontsource/ibm-plex-sans/600.css';
import '@xyflow/react/dist/style.css';
import './styles.css';
import './rich.css';
import './polish.css';
import './viewport.css';
import './graph-theme.css';
import './tech.css';
import './graph-tech.css';
import './minimal.css';
import './graph-refine.css';
import './cases-refine.css';
import { App } from './App';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
